### ISSUE TITLE
Patch: RequestProxy does not flush and release the resources

### ISSUE THREAD

**Issue by GoogleCodeExporter** [paultuckey/urlrewritefilter#101]
```
While using the RequestProxy I noticed that the output stream is not flushed 
which keeps the connection open with certain clients.

The attached patch corrects this. It is successfully used in production.
```

Original issue reported on code.google.com by `wallaby....@googlemail.com` on 25 Jan 2012 at 12:35

Attachments:
- [urlrewrite-proxy-flush-patch.diff](https://storage.googleapis.com/google-code-attachments/urlrewritefilter/issue-101/comment-0/urlrewrite-proxy-flush-patch.diff)

**Comment by paultuckey** [comment]
Stale.
