### ISSUE TITLE
reload servletContext

### ISSUE THREAD

**Issue by GoogleCodeExporter** [paultuckey/urlrewritefilter#141]
```
I use urlrewritfiler to redirect some requestes to another war(b.war). When I 
redeploy b.war, it can't redriect the request to b.war.


I have writen a patch and tested in Tomcat 6.0.29.
```

Original issue reported on code.google.com by `fanyunfe...@gmail.com` on 7 Jun 2013 at 7:20

Attachments:
- [context_reload.patch](https://storage.googleapis.com/google-code-attachments/urlrewritefilter/issue-141/comment-0/context_reload.patch)

**Comment by paultuckey** [comment]
Stale.
