### ISSUE TITLE
Patch for /trunk/src/test/test-web-adhoc/WEB-INF/urlrewrite.xml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [paultuckey/urlrewritefilter#145]
```
liljiluiluilui
```

Original issue reported on code.google.com by `chandu.p...@gmail.com` on 20 Jun 2013 at 6:01

Attachments:
- [urlrewrite.xml.patch](https://storage.googleapis.com/google-code-attachments/urlrewritefilter/issue-145/comment-0/urlrewrite.xml.patch)

**Comment by paultuckey** [comment]
Stale.
