### ISSUE TITLE
java.lang.NullPointerException UrlRewriteFilter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [paultuckey/urlrewritefilter#155]
```
Visiting http://127.0.0.1/WMTS/rewrite-status,error tips as follows:
java.lang.NullPointerException
    org.tuckey.web.filters.urlrewrite.Status.showHeader(Status.java:314)
    org.tuckey.web.filters.urlrewrite.Status.displayStatusInContainer(Status.java:78)
    org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.showStatus(UrlRewriteFilter.java:473)
    org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:373)

But on some computer,the same configuraiton succeed,why?


```

Original issue reported on code.google.com by `304851...@qq.com` on 13 Jan 2014 at 1:47

**Comment by ieugen** [comment]
+1 same issue

**Comment by karsumit94** [comment]
you should add http://cdn.rawgit.com/paultuckey/urlrewritefilter/master/src/doc/manual/4.0/urlrewrite.xml 
this file in WEB-INF get resolve this error

**Comment by santakdalai90** [comment]
Is there a way to keep urlrewrite.xml in conf folder in tomcat rather than keeping in a Servlet. The reason being I need redirection at root level. i.e. I want to redirect 127.0.0.1/xyz to 127.0.0.1/abc

**Comment by paultuckey** [comment]
Stale.
