### ISSUE TITLE
ModRewrite conditions don't support flags

### ISSUE THREAD

**Issue by GoogleCodeExporter** [paultuckey/urlrewritefilter#159]
```
What steps will reproduce the problem?
RewriteCond %{HTTP_HOST} ^(.*)from\\.com$ [NC]

What is the expected output? What do you see instead?
the [NC] should be parsed as a flag and properly set case insensitivity.

What version of the product are you using? On what operating system?
4.0.4

Please provide any additional information below.
The flags should be parsed similarly to the Rule flag parsing.

```

Original issue reported on code.google.com by `billapep...@gmail.com` on 16 Jun 2014 at 7:17

**Comment by billapepper** [comment]
I forked this project before it was on github and fixed this here: https://github.com/safarijv/urlrewritefilter/commit/cb9e18f350c6c4b31a77c47e008afa33826ec830

**Comment by paultuckey** [comment]
Hi @billapepper I'm happy to merge this and other fixes you made for urlrewrite into the codebase.  Would you like to do a pull request?

**Comment by paultuckey** [comment]
Stale.
