### ISSUE TITLE
Include license header in source files

### ISSUE THREAD

**Issue by puntogil** [paultuckey/urlrewritefilter#188]
./main/java/org/tuckey/web/filters/urlrewrite/functions/CssVarFunction.java
./main/java/org/tuckey/web/filters/urlrewrite/functions/StringFunctions.java
./main/java/org/tuckey/web/filters/urlrewrite/sample/SampleConfExt.java
./main/java/org/tuckey/web/filters/urlrewrite/sample/SampleMultiUrlRewriteFilter.java
./main/java/org/tuckey/web/filters/urlrewrite/substitution/ChainedSubstitutionFilters.java
./main/java/org/tuckey/web/filters/urlrewrite/substitution/SubstitutionContext.java
./main/java/org/tuckey/web/filters/urlrewrite/substitution/SubstitutionFilter.java
./main/java/org/tuckey/web/filters/urlrewrite/substitution/SubstitutionFilterChain.java
./main/java/org/tuckey/web/filters/urlrewrite/utils/ModRewriteConfLoader.java
./main/java/org/tuckey/web/filters/urlrewrite/utils/TypeUtils.java
./main/java/org/tuckey/web/filters/urlrewrite/utils/URLDecoder.java
./main/java/org/tuckey/web/filters/urlrewrite/utils/URLEncoder.java
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite1.0.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite2.0.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite2.3.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite2.4.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite2.5.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite2.6.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite3.0.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite3.1.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite3.2.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite3.3.dtd
./main/resources/org/tuckey/web/filters/urlrewrite/dtds/urlrewrite4.0.dtd

All java and dtd files, listed above, are without license headers.
Please, confirm the licensing of code and/or content/s
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by paultuckey** [comment]
Fixing here: https://github.com/paultuckey/urlrewritefilter/pull/255
