### ISSUE TITLE
notequals documented as numeric only

### ISSUE THREAD

**Issue by fejese** [paultuckey/urlrewritefilter#200]
The `notequals` operator is defined as follows:

> Not equal to. (i.e. request value != condition value). Note, this operator only work numeric rule types.

However my experience is that it works just well with non-numeric operands, for example with `scheme` or `host`.

We use this to ensure that the application is loaded with FQDN over https:

```
<urlrewrite>
  <rule>
    <condition name="host" operator="notequal">subdomain.example.com</condition>
    <from>^/(.*)</from>
    <to type="redirect" last="true">https://subdomain.example.com/$1</to>
  </rule>
  <rule>
    <condition type="scheme" operator="notequal">https</condition>
    <from>^/(.*)</from>
    <to type="permanent-redirect" last="true">https://subdomain.example.com/$1</to>
  </rule>
</urlrewrite>
```

Despite that the documentation suggests otherwise, the `notequal` works just fine, so I assume that the documentation needs and update.

**Comment by paultuckey** [comment]
Cleanup.  Was merged 3 years ago!
