### ISSUE TITLE
Logging Defaults

### ISSUE THREAD

**Issue by ksmith97** [paultuckey/urlrewritefilter#204]
It was quite a painful experience first using this library trying to debug why it was not working as expected when it by default produces no logs.  I understand that logging can be a tricky topic but having either a more verbose logging level by default or including a message somewhere other than deep in the docs(Notably in a easily searchable location) on how to configure it would have saved me a lot of time. Once I got some logging it worked beautifully though, so good work!

**Comment by hkarakose** [comment]
How did you enable logs?

**Comment by ksmith97** [comment]
If you check the latest documentation for Filter Parameters it is documented there.  Going to close this ticket since its now documented
