### ISSUE TITLE
jar download url is not working

### ISSUE THREAD

**Issue by farhansuno** [paultuckey/urlrewritefilter#206]
Hi,

I am not able to download the .jar file. 
The url - http://urlrewritefilter.googlecode.com/files/urlrewritefilter-4.0.3.jar  shows error 404.

Please help me with this.

Thanks,
Farhan

**Comment by halfninja** [comment]
You can find downloads at https://github.com/paultuckey/urlrewritefilter/releases

**Comment by halfninja** [comment]
http://central.maven.org/maven2/org/tuckey/urlrewritefilter/4.0.4/urlrewritefilter-4.0.4.jar
