### ISSUE TITLE
request-filename check fails with UTF-8 characeters

### ISSUE THREAD

**Issue by bdw429s** [paultuckey/urlrewritefilter#218]
Consider this rule means to enforce a front controller for all requests that aren't to an existing file:
```xml
<urlrewrite decode-using="null">
	<rule>
		<from>^/(.+)$</from>
		<to type="passthrough">/index.cfm/$1</to>
		<condition type="request-filename" operator="notfile"/>
	</rule>
</urlrewrite>
```
In this example I have a file called `gemüse.html` which exists in the webroot and I hit the URL `http://127.0.0.1/gemüse.html`.

The rule above should _not_ fire since the file path exists, however the rule is firing and here are the abbreviated logs:
```
UrlRewriter DEBUG: processing request for /gemüse.html
RuleBase DEBUG: Rule 0 run called with /gemüse.html
RuleBase DEBUG: matched "from"
Condition DEBUG: fileName found is C:\sandbox\bradfootest\gem%C3%BCse.html
Condition DEBUG: checking to see if C:\sandbox\bradfootest\gem%C3%BCse.html is not a file
Condition TRACE: outcome true
RuleBase DEBUG: conditions match
substitution.MatcherReplacer DEBUG: found 1
substitution.MatcherReplacer DEBUG: replaced sb is /index.cfm/gemüse.html
RuleExecutionOutput DEBUG: needs to be forwarded to /index.cfm/gemüse.html
UrlRewriter TRACE: got a rewritten url
RewrittenUrl TRACE: doRewrite called
```

I assume this is related to the fact that the file name is being converted to `gem%C3%BCse.html`.  I've tried adding `decode-using="null"` to the `<urlrewrite>` tag, but it has no effect.

**Comment by bdw429s** [comment]
https://github.com/paultuckey/urlrewritefilter/pull/250

**Comment by paultuckey** [comment]
#250 has been merged.  Assuming this is now fixed.
