### ISSUE TITLE
Security Vulnerabilities in urlrewritefilter

### ISSUE THREAD

**Issue by djbilo** [paultuckey/urlrewritefilter#219]
Am interested in sharing, for debugging purposes, vulnerability scan of the source code of this handy tool.

Please reach out if there is a way to share the report privately with the developer (only) - the information is highly confidential.

**Comment by paultuckey** [comment]
Hi, that would be great, please email it to me at paulATtuckey.org . (replace the AT in the email).

**Comment by alexsheppard11** [comment]
Were the vulnerabilities resolved?

**Comment by paultuckey** [comment]
No report ever arrived, @djbilo did you send it to me?

**Comment by djbilo** [comment]
I thought we sent it.    I'll see if I can get a new scan and send.



Regards,

David Bilodeau
Senior Member Technical Staff

Enterprise Solutions I.T.

600 Hidden Ridge
Mail Stop HQE01J92

O 972-457-8082** | M 972-849-2334
david.bilodeau@verizon.com
