### ISSUE TITLE
Proxy mode adds duplicate headers

### ISSUE THREAD

**Issue by grauds** [paultuckey/urlrewritefilter#228]
I use URL rewrite filter with Spring CORS filter and I'm getting a response with some headers duplicated. This happens because URL rewrite filter adds response headers, not just replaces them. I'm attaching a fix to this issue to consider including this to the next update or rejecting if is found improper:

`         hsResponse.setHeader(h.getName(), h.getValue());`

[RequestProxy.zip](https://github.com/paultuckey/urlrewritefilter/files/1867884/RequestProxy.zip)

**Comment by chadlwilson** [comment]
This was fixed with #229 so think can be closed
