### ISSUE TITLE
Documentation is being returned as Content-Type: text/plain

### ISSUE THREAD

**Issue by chubbard** [paultuckey/urlrewritefilter#243]
Goto the User Manual

https://cdn.jsdelivr.net/gh/paultuckey/urlrewritefilter@master/src/doc/manual/4.0/index.html

The browser does not render it as HTML because the Content-Type returned is "text/plain".  Any chance that could get fixed?

**Comment by paultuckey** [comment]
Weird.  That seems to just be a mirror of files from GitHub: https://cdn.jsdelivr.net/gh/paultuckey/urlrewritefilter@master/

I guess that is a `jsdelivr.net` decision to deliver html as `text/plain`.

**Comment by chubbard** [comment]
Sorry I guess I wasn't clear enough.  If you goto the home page:

https://tuckey.org/urlrewrite/#documentation

And click on the link (4.0 user manual) to the documentation it is served up as plain/text.  You can't actually view the documentation as html which is very difficult to read as text.  The link on 4.0 user manual is this:

http://cdn.rawgit.com/paultuckey/urlrewritefilter/master/src/doc/manual/4.0/index.html

Somehow that redirects to  cdn.jsdelivr.net link which ultimately serves it up as plain/text.  

The documentation is basically unreadable from the home page.

**Comment by paultuckey** [comment]
fixed now https://tuckey.org/urlrewrite/manual/4.0/index.html
