### ISSUE TITLE
Query related to latest version of urlrewritefilter jar in maven central repository

### ISSUE THREAD

**Issue by sahithpaidi** [paultuckey/urlrewritefilter#244]
In Maven central the latest version of urlrewritefilter jar is 4.0.4, which is published in 2012. In the GitHub we see there are many improvements in recent times. 
1. In master branch(pom.xml) we see the version is 5.0.0-SNAPSHOT, which is not available in the maven repository.
2. Is there any latest version after 4.0.4 we can find anywhere else?
3. Is there any recommendations to checkout the source and build the jar ourselves?

https://mvnrepository.com/artifact/org.tuckey/urlrewritefilter/4.0.4

**Comment by glorieux-f** [comment]
Compiling with maven and an openJdk 11 gave me an error.

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error: Source option 5 is no longer supported. Use 6 or later.
[ERROR] error: Target option 1.5 is no longer supported. Use 1.6 or later.

Modify pom.xml l.72-73 solve the pb
&lt;configuration>
    &lt;source>1.6&lt;/source>
    &lt;target>1.6&lt;/target>
&lt;/configuration>

**Comment by paultuckey** [comment]
Related to PR: https://github.com/paultuckey/urlrewritefilter/pull/249

**Comment by paultuckey** [comment]
I don't think this is an issue any longer.
