### ISSUE TITLE
jakarta classifier versions of the jars are missing on the Central Maven Repository

### ISSUE THREAD

**Issue by hvanrobays** [paultuckey/urlrewritefilter#251]
Hello,

The jakarta classifier versions of the jars are missing on the Central Maven Repository:
https://repo1.maven.org/maven2/org/tuckey/urlrewritefilter/4.0.4/ 
https://repo1.maven.org/maven2/org/tuckey/urlrewritefilter/4.0.3/

When using the following maven dependency, maven cannnot find the Jakarta version of the jar either:
        <dependency>
            <groupId>org.tuckey</groupId>
            <artifactId>urlrewritefilter</artifactId>
            <version>4.0.4</version>
            <classifier>jakarta</classifier>
        </dependency>

Could you please also upload the jakarta versions to the central repo?

Kind regards,
HV

**Comment by kicktipp** [comment]
Yes, I need this, too. Very important.

**Comment by XavierSamuelHuppe** [comment]
I do also need this

**Comment by hink084** [comment]
The PR (#242) for the jakarta classifier wasn't integrated into master until February 21, 2023.  v4.0.4 was released in 2012.  The Readme.md was incorrectly updated to state that you can add the jakarta classifier to v4.0.3.  I had to build the 5.0.0-SNAPSHOT to obtain access to the jakarta JAR.

**Comment by paultuckey** [comment]
FYI I'm working on making the whole library work on the `jakarta` package in this PR https://github.com/paultuckey/urlrewritefilter/pull/248

**Comment by jetztgradnet** [comment]
@paultuckey thanks for your work on updating urlrewritefilter and bringing it into the new age!

Would you care to share some rough timeline on when you are planning to publish this? Any further help that can be done to get the release with the Jakarta migration out of the door?

**Comment by paultuckey** [comment]
I'm keen to publish a beta, however I'm struggling with the process.  There is a lot of conflicting documentation.  Do you know where I can the up to date process for publishing a beta to mvncentral?

**Comment by jetztgradnet** [comment]
Unfortunately Not, I have never done this myself. 
If you do not insist on uploading the beta build to Maven Central,
You might simply publish as a GitHub release and ask for people to test this?
Loading the beta release using direct URL access would also be possible from Maven (I think) and Gradle (definitely).

**Comment by paultuckey** [comment]
Ok, skipping maven central for now.

Hopefully this works: https://github.com/paultuckey/urlrewritefilter/packages/1899789

**Comment by zyc** [comment]
It seems someone already published the package changing in Maven Central Repo using a personal groupId, not with the `org.tuckey`. Actually it will be necessary to do the work unless someone here have the credentials to publish on `org.tuckey` groupId. It works like a protected domain.

So I downloaded the regular and the Jakarta classifier jar files. The corrections are there but I've not tested it yet.

The direct link to the Maven Repo is:

https://central.sonatype.com/artifact/de.knightsoft-net/urlrewritefilter/4.0.4.1/versions

And the compiled jar files:

https://repo1.maven.org/maven2/de/knightsoft-net/urlrewritefilter/4.0.4.1/

And the dependency declaration to put into pom.xml:

```
<dependency>
    <groupId>de.knightsoft-net</groupId>
    <artifactId>urlrewritefilter</artifactId>
    <version>4.0.4.1</version>
    <classifier>jakarta</classifier>
</dependency>
```

To be clear: I'm not the author. Just sharing what I found about that.

**Comment by jetztgradnet** [comment]
@paultuckey quick question: are you still planning to release the new Jakarta-based binary artifact on Maven Central? Getting the SNAPSHOT release from GitHub packages works, but having an official release would be a great improvement.
Thanks for your consideration, time and effort!

**Comment by kicktipp** [comment]
Still not working.

**Comment by paultuckey** [comment]
@jetztgradnet and others, I'm keen to publish to mvncentral, however I'm struggling with the process. There is a lot of conflicting documentation. Do you know where I can the up to date process for publishing a beta to mvncentral?

**Comment by paultuckey** [comment]
I've managed to deploy a snapshot here:
https://oss.sonatype.org/content/repositories/snapshots/org/tuckey/urlrewritefilter/5.1.0-SNAPSHOT/

Can you verify this works please @jetztgradnet?

**Comment by jetztgradnet** [comment]
@paultuckey fetching this 5.1-SNAPSHOT version works for me.
I have added this section into my `build.gradle` file:

```
repositories {
   mavenCentral()
   maven { 
      // urlrewritefilter is not available in maven central
      url "https://oss.sonatype.org/content/repositories/snapshots"
      content {
         // this repository *only* contains artifacts for a few libraries with snapshot versions
         includeGroup "org.tuckey"
   }
}
```

The whole process of publishing the artifeact in Maven Central is described at https://central.sonatype.org/publish/ and the step-by-step guide is located at https://central.sonatype.org/publish/publish-guide/. Does that help?

BTW, will the JakartaEE-based version be published as 5.0 or 5.1?

**Comment by paultuckey** [comment]
Thanks, that is helpful.

> will the JakartaEE-based version be published as 5.0 or 5.1?

@jetztgradnet was thinking 5.0, which do you prefer?

**Comment by jetztgradnet** [comment]
At the end I do not care too much, I was just wondering on why using 5.1 as there was no 5.0, right?

Thanks again for your time and effort!

**Comment by paultuckey** [comment]
5.1.1 is here now: https://repo1.maven.org/maven2/org/tuckey/urlrewritefilter/

LMK if that works ok.  I've had a lot of trouble setting it up.

**Comment by firatkucuk** [comment]
Hey Paul, can you add a git tag for 5.1.1? We are maintaining a forked version of this.

**Comment by paultuckey** [comment]
Thanks @firatkucuk I've tagged.  There is a PR open for readme/docs update.

**Comment by firatkucuk** [comment]
Thanks Paul

**Comment by jetztgradnet** [comment]
also thanks from us, @paultuckey, to have the Jakarta-ready version up on Maven Central! Very much appreciated!
